name: Ellenay
markdown: redcarpet
url: http://ellenay.co.uk
pygments: true
paginate: 5
paginate_path: "/page-:num"
exclude: ['CNAME', 'bower_components', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'assets/css/*.less', 'bin']
